ShowCommandScreen -Heading 'Welcome to DevTools' -Description @(
    'DevTools helps you manage your development workspace from one place.'
    'Built for developers who want a calm, menu-first way to work with GitHub projects on Windows.'
)

ShowSection -Label 'What is DevTools?'
ShowInfo 'A friendly workspace manager for cloning, updating, checking, backing up, and opening your projects.'

ShowSection -Label 'Who is it for?'
ShowInfo 'Anyone who wants to spend less time managing repositories and more time building.'

ShowSection -Label 'Recent Projects'
ShowInfo 'DevTools remembers projects you open most often.'
ShowInfo 'Run: dev recent'
ShowInfo 'Press O on Home to quickly open a recent project.'

ShowSection -Label 'Project Info'
ShowInfo 'Inspect a project without leaving DevTools.'
ShowInfo 'Run: dev info'
ShowInfo 'Run: dev info walkreplay'

ShowSection -Label 'Repository Intelligence'
ShowInfo 'Keep a large workspace healthy without risking local work.'
ShowInfo 'Run: dev sync      (refresh GitHub state, safely fast-forward what it can)'
ShowInfo 'Run: dev status    (Repository Health - what needs attention?)'
ShowInfo 'Run: dev repos     (repair upstreams, clean merged branches, export reports)'
ShowInfo 'dev update still works and does the same thing as dev sync.'
ShowInfo 'Sync is fast-forward only. It never stashes, resets, merges, commits, or pushes for you.'

ShowSection -Label 'Typical workflow'
ShowInfo '1. Configure your workspace.'
ShowInfo '2. Run Doctor.'
ShowInfo '3. Clone repositories.'
ShowInfo '4. Open a project.'
ShowInfo '5. Build.'
ShowInfo '6. Backup your work.'
ShowInfo '7. Sync repositories regularly.'

ShowSection -Label 'Quick Actions'
ShowInfo 'Quick Actions are for the tasks you run most often:'
ShowInfo 'Open recent, search projects, view repository health, sync, or clone.'
ShowInfo 'Run: dev quick'

ShowSection -Label 'Open Project search'
ShowInfo 'When opening a project, search by partial name.'
ShowInfo 'Example: search "walk" to find WalkReplay and similar folders.'
ShowInfo 'Run: dev open walkreplay'

ShowSection -Label 'Deployment Manager'
ShowInfo 'Find every website you have on GitHub and compare it with Vercel.'
ShowInfo 'Run: dev deploy audit    (read-only)'
ShowInfo 'Run: dev deploy plan     (read-only preview of what would be created)'
ShowInfo 'Run: dev deploy sync     (creates Vercel projects after you approve)'
ShowInfo 'Run: dev deploy verify   (read-only production check)'
ShowInfo 'Vercel is optional. See docs/deployments.md to connect it.'

ShowSection -Label 'Automated validation'
ShowInfo 'Run the automated DevTools validation suite from any directory.'
ShowInfo 'Run: dev test'

ShowSection -Label 'Global install'
ShowInfo 'Add DevTools to your user PATH from any clone:'
ShowInfo 'Run: dev self install'
ShowInfo 'Check PATH status: dev self path'
ShowInfo 'Remove from PATH: dev self uninstall'

ShowSection -Label 'Quick Commands'
ShowInfo 'dev'
ShowInfo 'dev test'
ShowInfo 'dev quick'
ShowInfo 'dev recent'
ShowInfo 'dev info'
ShowInfo 'dev doctor'
ShowInfo 'dev status'
ShowInfo 'dev sync'
ShowInfo 'dev update'
ShowInfo 'dev repos'
ShowInfo 'dev clone'
ShowInfo 'dev open'
ShowInfo 'dev deploy'

ShowSection -Label 'Need more help?'
ShowInfo 'Visit the GitHub repository for documentation and updates:'
ShowInfo (Get-DevToolsRepositoryUrl)
ShowInfo 'See docs/commands.md for detailed command reference.'
